version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: crawling_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "10707:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: crawling_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "10708:80"
    depends_on:
      - db

  crawling:
    image: agong1/crawling_song:latest
    container_name: crawling_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - ./logs:/app/logs
      - ./csv_folder:/app/csv_folder
    command: >
      bash -c "
      pwd &&
      ls -la / &&
      ls -la /app &&
      service cron start &&
      python3 crawling_view/controller/run_crawling.py &&
      tail -f /dev/null
      "

volumes:
  db_data:
